### ISSUE TITLE
Crash when using the -a flag

### ISSUE THREAD

**Issue by abasu2** [DavisPL/cargo-sherlock#8]
The -a flag seems to not be working properly. Here's a traceback trying to use the -a flag on crate abomonation v0.7.3:
```
Solving for required Assumptions to trust abomonation-0.7.3...
Traceback (most recent call last):
  File "/home/abasu/reu/cargo-sherlock/sherlock.py", line 73, in <module>
    main()
  File "/home/abasu/reu/cargo-sherlock/sherlock.py", line 57, in main
    codex = subprocess.run([sys.executable, 'solver.py', args.crate_name, args.version , args.output])
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1796, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by muhammad-hassnain** [comment]
This was happening because of -o (output file) being required with the -a. I have changed -o to being optional.
